// Generated by CoffeeScript 1.6.3
var Cloner, Random, StrictMath, println, typeIsArray;

if (!Array.prototype.filter) {
  Array.prototype.filter = function(callback) {
    var element, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = this.length; _i < _len; _i++) {
      element = this[_i];
      if (callback(element)) {
        _results.push(element);
      }
    }
    return _results;
  };
}

if (typeof println === "undefined" || println === null) {
  if (typeof console !== "undefined" && console !== null) {
    println = console.log;
  }
  if (println == null) {
    println = java.lang.System.out.println;
  }
}

typeIsArray = function(value) {
  return value && typeof value === 'object' && value instanceof Array && typeof value.length === 'number' && typeof value.splice === 'function' && !(value.propertyIsEnumerable('length'));
};

if (typeof Random === "undefined" || Random === null) {
  Random = {};
  Random.nextInt = function(limit) {
    return Math.floor(Math.random() * limit);
  };
  Random.nextLong = Random.nextInt;
  Random.nextDouble = function() {
    return Math.random();
  };
}

Cloner = {
  clone: function(obj) {
    var key, temp, _i, _len, _ref;
    if (obj === null || typeof obj !== "object") {
      return obj;
    }
    temp = new obj.constructor();
    _ref = Object.getOwnPropertyNames(obj);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      key = _ref[_i];
      temp[key] = this.clone(obj[key]);
    }
    return temp;
  }
};

if (typeof StrictMath === "undefined" || StrictMath === null) {
  StrictMath = Cloner.clone(Math);
  StrictMath.toRadians = function(degrees) {
    return degrees * Math.PI / 180;
  };
  StrictMath.toDegrees = function(radians) {
    return radians * 180 / Math.PI;
  };
}
